title: DCCoder
author: DCCoder

# --- List of links in the navigation bar --- #
navbar-links:
  Home: "index"
  About Me: "aboutme"
  dEngine: "dengine/index.html"
  Resume: "resume"

# --- Logo --- #
avatar: "/assets/img/1702667160916.jpg"
round-avatar: true

# --- Footer social media links --- #

social-network-links:
  github: DCCoder90
  linkedin: dccoder
  stackoverflow: "8333554/dccoder"

rss-description: Just a guy who likes code.  Feel free to subscribe!

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "MyWebsite.com"
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true

# The keywords to associate with your website, for SEO purposes
keywords: "cloud,development,programming,dccoder,dccoder90,aws,engineer,architect,computers,it"

# --- Colours / background image --- #

##### Teal and Charcoal Theme
navbar-col: "#1D1D1D"
navbar-text-col: "#EAEAEA"
navbar-border-col: "#14B8A6"
page-col: "#121212"
text-col: "#EAEAEA"
link-col: "#14B8A6"
hover-col: "#2A2A2A"
footer-col: "#1D1D1D"
footer-text-col: "#A0A0A0"
footer-link-col: "#C0C0C0"
button-col: "#14B8A6"

##### Blue twitter'ish theme
#navbar-col: "#15202B"
#navbar-text-col: "#FFFFFF"
#navbar-border-col: "#205295"
#page-col: "#15202B"
#text-col: "#FFFFFF"
#link-col: "#8899A6"
#hover-col: "#22303C"
#footer-col: "#15202B"
#footer-text-col: "#8899A6"
#footer-link-col: "#8899A6"
#button-col: "#15202B"
remove-ads: true

# Suggest a color for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# --- Web Analytics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using Google Analytics
#google_analytics: ""

# Fill in your Cloudflare Analytics beacon token to track your website using Cloudflare Analytics
#cloudflare_analytics: ""

# Google Tag Manager ID
#gtm: ""

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  - scope:
      path: "" 
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189